#Script em YAML - template para criar uma máquina EC2 via CLI, por exemplo.

AWSTemplateFormatVersion: "2010-09-09"
Description: "Template CloudFormation para criar uma EC2 simples e barata (t2.micro)."

Parameters:
  KeyName:
    Description: Nome do par de chaves existente para acesso SSH
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Deve ser o nome de um par de chaves existente na sua conta.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Simples

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH de qualquer lugar
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Outputs:
  InstanceId:
    Description: ID da Instância EC2 criada
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: IP público da Instância
    Value: !GetAtt MyEC2Instance.PublicIp
